version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: 'nest-zookeeper'
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: 'nest-kafka'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'create-user:1:1, find-all-user:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    container_name: 'nest-bd'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db-nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
    volumes:
      - bd-nest-data:/data
    networks:
      - network-nest

volumes:
  bd-nest-data:

networks:
  network-nest:
    driver: bridge
